Repository Neph3779/ios-wanted-GyroData, pull requests merged in 2022-12, with the labels that each got.

#2 Feature/#1 GraphView 제작
  GyroData.xcodeproj/project.pbxproj
  GyroData/GraphView.swift
  GyroData/GraphViewModel.swift
  GyroData/ViewController.swift
Labels: Feat

#6 Feature/#5 entity제작
  GyroData.xcodeproj/project.pbxproj
  GyroData/Coordinate.swift
  GyroData/MotionMode.swift
  GyroData/MotionRecord.swift
Labels: Feat

#8 [Chore] #7 스토리보드 삭제, AppDelegate entry point 설정
  GyroData.xcodeproj/project.pbxproj
  GyroData/AppDelegate.swift
  GyroData/Base.lproj/Main.storyboard
  GyroData/Info.plist
  GyroData/SceneDelegate.swift
Labels: Chore

#11 Feature/#10 motion replay제작
  GyroData.xcodeproj/project.pbxproj
  GyroData/AppDelegate.swift
  GyroData/GraphView.swift
  GyroData/MotionReplayViewController.swift
  GyroData/MotionReplayViewModel.swift
  GyroData/ReplayType.swift
Labels: Feat

#13 Feature#4 motion recording view controller제작
  GyroData.xcodeproj/project.pbxproj
  GyroData/GraphView.swift
  GyroData/GraphViewModel.swift
  GyroData/MockMotionRecordingStorage.swift
  GyroData/MotionMode.swift
  GyroData/MotionRecordingStorageProtocol.swift
  GyroData/MotionRecordingViewController.swift
  GyroData/MotionRecordingViewModel.swift
  GyroData/SaveMotionDataUseCase.swift
Labels: Feat

#20 [Fix] 그래프의 테두리를 다크 모드에서 보이는 색으로 변경
  GyroData/Presentation/MotionReplay/MotionReplayViewController.swift
Labels: Chore

#19 Feature/#18 두번째 화면 수정
  GyroData/Data/MotionRecordingStorage.swift
  GyroData/Domain/UseCases/SaveMotionDataUseCase.swift
  GyroData/Presentation/Graph/GraphView.swift
  GyroData/Presentation/MotionRecording/MotionRecordingViewController.swift
  GyroData/Presentation/MotionRecording/MotionRecordingViewModel.swift
Labels: Feat

#21 Feature/#18 FileManager 통해 File 형식으로 저장 및 불러오기 기능 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Application/AppDelegate.swift
  GyroData/Data/CoordinateDTO.swift
  GyroData/Data/FileStorage.swift
  GyroData/Data/MotionDataListStorage.swift
  GyroData/Data/MotionRecordDTO.swift
  GyroData/Data/MotionRecordingStorage.swift
  GyroData/Data/MotionReplayStorage.swift
  GyroData/Domain/StorageInterfaces/MotionDataListStorageProtocol.swift
  GyroData/Domain/StorageInterfaces/MotionReplayStorageProtocol.swift
  GyroData/Domain/UseCases/FetchMotionDataListUseCase.swift
  GyroData/Domain/UseCases/FetchMotionDataUseCase.swift
  GyroData/Info.plist
  GyroData/Presentation/MotionDataList/MotionDataListViewController.swift
  GyroData/Presentation/MotionDataList/MotionDataListViewModel.swift
  GyroData/Presentation/MotionReplay/MotionReplayViewController.swift
  GyroData/Presentation/MotionReplay/MotionReplayViewModel.swift
Labels: Feat

#23 [Refactor] #22 사용하지 않게된 msInterval 삭제 및 저장하는 확장자명 변경
  GyroData/Application/AppDelegate.swift
  GyroData/Data/FileStorage.swift
  GyroData/Data/MotionData.xcdatamodeld/MotionData.xcdatamodel/contents
  GyroData/Data/MotionRecordDTO.swift
  GyroData/Data/MotionRecordEntity+CoreDataProperties.swift
  GyroData/Data/MotionRecordingStorage.swift
  GyroData/Domain/Entities/MotionRecord.swift
  GyroData/Presentation/MotionRecording/MotionRecordingViewController.swift
  GyroData/Presentation/MotionRecording/MotionRecordingViewModel.swift
Labels: Refactor
